### ISSUE TITLE
Windows crash when selecting a new requirement version

### ISSUE THREAD

**Issue by Adnn** [ShredEagle/shred-project-helper#10]
Here is the traceback:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Scripts\sph.exe\__main__.py", line 7, in <module>
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sph\tui.py", line 471, in tui
    runner.run_ui()
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sph\tui.py", line 399, in run_ui
    curses.wrapper(self.main_loop)
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sph\tui.py", line 284, in main_loop
    self.resolve_conflict_item(conflict_ref, ws)
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sph\tui.py", line 357, in resolve_conflict_item
    self.resolve_conflict(self.editable_list, conflict_ref, ws)
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sph\tui.py", line 369, in resolve_conflict
    version_changed = editable.change_version(selected_conflict_ref)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sph\editable.py", line 146, in change_version
    with open(self.conan_path, "rU") as conanfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```

**Comment by FranzPoize** [comment]
Should be fixed by 0b436d845d0
